config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  get 'users/edit'

  devise_for :users
  root to: 'homes#top'
  get 'homes/about'

  resources :posts
  resources :users,only: [:show, :edit, :index, :update]

# 追加　名前つきルーティング

# mypage
  get "mypage"=>"users#mypage"

# 退会確認
  get 'users/:id/quit' => 'users#quit', as: 'quit'

# 退会処理用
  patch 'users/:id/withdrawal' => 'users#withdrawal', as: 'withdrawal'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
 has_one_attached :image

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
     user_path(current_user.id)
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def new
    @post_new = Post.new
  end

  def create
     @post_new = Post.new(post_params)
    # @post_new = Post.new(params[:id])　→→これだとnilが渡る(照合するidがないから？)

    # 感情分析スコアの作成
    @post_new.score = Language.get_data(post_params[:body])

     if @post_new.user_id = current_user.id
      @post_new.save

      # tags = Vision.get_image_data(@post_new.image)
      #   tags.each do |tag|
      #   @post_new.tags.create(name: tag)
      #   end



      redirect_to post_path(@post_new.id)
      # @post_new.idとすることで、新規に与えられたidをもとに詳細ページへ飛べる
     end
  end

  def index
    # whereにより、投稿したユーザーのデータのみを出力させる
    @posts = Post.where(user_id: current_user.id).includes(:user).order("created_at DESC")
    @user = current_user
  end

  def show
    @post = Post.find(params[:id])
  end

  def edit
    @post = Post.find(params[:id])

  end

  def update
    @post = Post.find(params[:id])

     if @post.update(post_params)
        flash[:notice]="You have updated successfully."
        redirect_to post_path(@post.id)

     else
        render "edit"
     end

  end

  def destroy
    post = Post.find(params[:id])

    post.destroy
      flash[:notice]="Post was successfully destroyed."
      redirect_to posts_path

  end


  private

  def post_params
    params.require(:post).permit(:title,:body,:image)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    # whereにより、投稿したユーザーのデータのみを出力させる
    @posts = Post.where(user_id: current_user.id).includes(:user).order("created_at DESC")

  end

  def edit
     @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])

     if @user.update(user_params)
        flash[:notice]="You have updated successfully."
        redirect_to mypage_path

     else
        render "edit"
     end
  end



def mypage
  @user = current_user
end



def quit
    @user = current_user
end


def withdrawal
    @user = current_user
    # is_deletedカラムをtrueに変更することにより削除フラグを立てる
    @user.update(is_deleted: true)
    reset_session
    redirect_to root_path, notice: "退会処理を実行いたしました。ご利用いただき、誠にありがとうございました"
 end

 private

  def user_params
    params.require(:user).permit(:name, :email)
  end

  def post_params
    params.require(:post).permit(:title,:body,:image)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/homes/about.html.erb
<h1>dairyとは</h1>
<p>
  その名の通り、日記です。<br />
  日記として開発していますが、メモとしても利用できるアプリです。<br />
  投稿から、あなたの感情スコアを読み取ることもできます。<br />
  メモとして使うもよし、日記として感情の整理に使うもよし、使い方はあなた次第です。
</p>

<%= link_to "back",root_path %>

app/views/homes/top.html.erb
<h1>Homes#top</h1>
<p>今日の気分を書き出して、スッキリしていきませんか?</p>

<p><%= link_to "dairyとは",homes_about_path %></p>


<p><%= link_to "ログイン",new_user_session_path %></p>
<p>新規登録はこちら</p>
<%= link_to "新規登録", new_user_registration_path %>

app/views/layouts/_header.html.erb
<body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown"
                        aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
          <% if user_signed_in? %>
           <li><i class="fas fa-sign-out-alt"></i></i><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
           <li><i class="fas fa-pen"></i></i><%= link_to "新規投稿",new_post_path %></li>
           <li><i class="fas fa-users-cog"></i><%= link_to "ユーザー情報",mypage_path %></li>
           <li><i class="fas fa-times"></i><%= link_to "退会する",quit_path(current_user.id) %></li>


          <% else %>
          <li>
            <%= link_to"トップページへ",root_path, class:"link" %>
          </li>
          <li>
            <%= link_to"サインアップ", "/users/sign_up", class:"link" %>
          </li>
          <li>
            <%= link_to"ログイン", "/users/sign_in", class:"link" %>
          </li>
         <% end %>
         </ul>
          </div>
        </div>
      </nav>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Diary</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <main>
     <%= render "layouts/header" %>
     <%= yield %>
    </main>
  </body>
</html>

app/views/posts/edit.html.erb
<h1>Posts#edit</h1>

 <%= form_with model: @post, url: post_path(@post.id), method: :patch do |f|  %>

     <div class="form-group">
      <%= f.label :title,"タイトル" %><br>
      <%= f.text_field :title,class: "w-100" %><br/>
     </div>

    <div class="form-group">
       <%= f.label :image,"写真" %><br>
       <%= f.file_field :image,accept: "image/*" %><br />
   </div>

    <div class="form-group">
      <%= f.label :body,"本文" %><br/>
      <%= f.text_area :body,rows: '5',class: "w-100" %><br/>
    </div>

     <%= f.submit '投稿する' %>
    <% end %>
    </div>
  </div>

app/views/posts/index.html.erb
<h1><%= @user.name %>の投稿一覧</h1>
<% @posts.each do |post| %>
 <%= link_to post.title,post_path(post.id) %>
 <%= post.body %>
 <% if post.image.attached? %>
  <%= image_tag post.image, size: "300x300" %>
<% end %>
 <%#= post.created_at %>    <!--このコードだとUTC表示になるので、下記に変更-->
 <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
<% end %>

app/views/posts/new.html.erb
<h1>新規投稿</h1>
<p>お疲れ様です。今の気持ちやアイデアを、記録に残しませんか？</p>

 <%= form_with model: @post_new, url: '/posts',method: :post do |f|  %>

     <div class="form-group">
      <%= f.label :title,"タイトル" %><br>
      <%= f.text_field :title,class: "w-100" %><br/>
     </div>

    <div class="form-group">
       <%= f.label :image,"写真" %><br>
       <%= f.file_field :image,accept: "image/*" %><br />
   </div>

    <div class="form-group">
      <%= f.label :body,"本文" %><br/>
      <%= f.text_area :body,rows: '5',class: "w-100" %><br/>
    </div>

     <%= f.submit '投稿する' %>
    <% end %>
    </div>
  </div>

app/views/posts/show.html.erb
<h1>Posts#show</h1>
<%= @post.title %>
<%= @post.body %>
<span class="sentiment-score">感情スコア<%= @post.score %></span>

<% if @post.image.attached? %>
  <%= image_tag @post.image, size: "300x300" %>
<%# else %>
  <%#= image_tag 'no_image.jpg', size: "300x300" %>
<% end %>

<%= @post.created_at.strftime('%Y/%m/%d %H:%M') %>

<%= link_to "edit",edit_post_path(@post) %>
<%= link_to "destroy",post_path,method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-danger" %>

<%= link_to "back",posts_path %>

app/views/users/edit.html.erb
<h1>Users#edit</h1>


 <%= form_with model: @user, url: user_path(@user.id), method: :patch do |f|  %>

 <div class="form-group">
      <%= f.label :name,"名前" %><br>
      <%= f.text_field :name,class: "w-100" %><br/>
     </div>


    <div class="form-group">
      <%= f.label :email,"メールアドレス" %><br>
      <%= f.text_field :email,class: "w-100" %><br/>
    </div>

     <%= f.submit '投稿する' %>
    <% end %>
    </div>
  </div>

 <div>
  <%= link_to "退会する",quit_path %>
 </div>

app/views/users/mypage.html.erb
<%= @user.name %>のユーザー情報

<%= @user.name %>
<%= @user.email %>
<%= @user.created_at.strftime('%Y/%m/%d %H:%M') %>
<%= link_to "ユーザー情報を編集する",edit_user_path(@user.id) %>
<%= link_to "日記の一覧に戻る",posts_path %>

app/views/users/quit.html.erb
<h2>退会確認</h2>
     <br>
     退会されますと、全てのサービスがご利用いただけなくなります。<br />
   　再度ご利用をいただく場合には、新規登録のお手続きが必要になります。<br />
   　本当に退会してよろしいですか？<br />
     退会する場合は、「退会する」をクリックしてください。

     <div class="row py-5 mr-2 form-group justify-content-center">
      <%= link_to "退会する",withdrawal_path, method: :patch,data: { confilm: "この操作は取り消せませんが、よろしいですか？" }, class:"btn btn-danger mr-5 px-4" %>
      <%= link_to "退会しない",user_path(current_user),class:"btn btn-success mr-5 px-4" %>
    </div>

app/views/users/show.html.erb
<h1><i class="fas fa-book"></i><%= @user.name %>の投稿一覧</h1>
<% @posts.each do |post| %>
 <%= link_to post.title,post_path(post.id) %>
 <%= post.body %>

 <% if post.image.attached? %>
  <%= image_tag post.image, size: "300x300" %>

<% end %>
 <%#= post.created_at %>    <!--このコードだとUTC表示になるので、下記に変更-->
 <%= post.created_at.strftime('%Y/%m/%d %H:%M') %>
<% end %>



<%= link_to "プロフィール編集",edit_user_path(@user.id) %>